### PR TITLE
refactor: write [T]Value in terms of [T]ValueDetails

### PR DESCRIPTION
**Pull request by craigpastro**
## This PR

Rewrite all the [T]Value functions in terms of [T]ValueDetails functions to reduce duplication. [T]ValueDetails is not anything significantly much more than [T]Details.

By the way, I noticed this while I was looking at the code to see if it could be genericizied (#158) and it seems like it can, but it is a bit tricky I think.

### CODE REVIEW

**Comment by beeme1mr** [comment]
Hey @craigpastro, yeah it looks like CodeCov prematurely released v4, and Renovate updated it.

https://github.com/codecov/codecov-action/issues/1089

I've reverted CodeCov back to v3.

**Comment by craigpastro** [comment]
> Hey @craigpastro, yeah it looks like CodeCov prematurely released v4, and Renovate updated it.
> 
> [codecov/codecov-action#1089](https://github.com/codecov/codecov-action/issues/1089)
> 
> I've reverted CodeCov back to v3.

Thanks @beeme1mr 🙌

**Comment by toddbaert** [comment]
I'll try to review this today/tomorrow!

**Comment by craigpastro** [comment]
Thanks, Todd. No rush of course.

**Review by toddbaert — APPROVED** [review]
Love it, thanks!

**Pull request merged**
