### PR TITLE
chore: update comments for named provider related function

### PR DESCRIPTION
**Pull request by yongruilin**
## This PR

Update comments for named provider related functions.

### Related Issues

N/A

### Notes
Only updates comments.

### Follow-up Tasks
N/A

### How to test
N/A

### CODE REVIEW

**Comment by yongruilin** [comment]
@beeme1mr, @Kavindu-Dodan   PTAL, thanks!

**Review by beeme1mr — APPROVED** [review]

**Comment by beeme1mr** [comment]
Thanks @yongruilin! Could you please sign off your commits? It's a requirement from the CNCF before we can merge.

**Comment by beeme1mr** [comment]
It looks like there's an unrelated build error. I'll look into it tomorrow.

Fyi @toddbaert @thisthat @Kavindu-Dodan

**Comment by thisthat** [comment]
> It looks like there's an unrelated build error. I'll look into it tomorrow.
> 
> Fyi @toddbaert @thisthat @Kavindu-Dodan

I guess it is the same problem identified by @Kavindu-Dodan in the contrib repo: https://github.com/open-feature/go-sdk-contrib/pull/317/files#r1306174491

**Comment by toddbaert** [comment]
I've opened https://github.com/open-feature/go-sdk/pull/216 to fix the ci issue.

**Review by toddbaert — APPROVED** [review]

**Pull request merged**
