### PR TITLE
chore: bump spec badge in readme to v0.7.0

### LINKED ISSUE #217: Conform to spec `v0.7.0`
Update the SDK to be compliant with `v0.7.0`.

- [x] ensure compliance with all point in `v0.7.0` (see [here](https://github.com/open-feature/spec/releases/tag/v0.7.0) for list of changes) 
  - [x] #220
  - [x] add new STALE provider state
  - [x] add `provider name` to `event details`
- [x] implement relevant tests
- [x] update spec badge in README.md

> [!NOTE]
> the Go SDK may already implement some of these - for instance I believe the provider-name is already present in event details.

### PR DESCRIPTION
**Pull request by craigpastro**
## This PR

Bump spec badge in readme to v0.7.0.

### Related Issues

Closes #217.

### CODE REVIEW

**Comment by toddbaert** [comment]
@craigpastro can you add some test coverage for this?

**Comment by toddbaert** [comment]
> @craigpastro can you add some test coverage for this?

(just kidding)

**Comment by craigpastro** [comment]
> @craigpastro can you add some test coverage for this?

LOL

**Comment by Kavindu-Dodan** [comment]
@craigpastro thanks for the PR 

@toddbaert this needs to be merged with the latest go-sdk release - https://github.com/open-feature/go-sdk/pull/215 . We could merge both on Monday

**Review by Kavindu-Dodan — APPROVED** [review]

**Review by beeme1mr — APPROVED** [review]

**Pull request merged**
